%% Generated by the Erlang ASN.1 compiler. Version: 5.3.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module FruitModuleV1.

-ifndef(_FRUITMODULEV1_HRL_).
-define(_FRUITMODULEV1_HRL_, true).

-record('FruitSalad', {
  fruits,
  servingSize
}).

-endif. %% _FRUITMODULEV1_HRL_
