%% Generated by the Erlang ASN.1 compiler. Version: 5.3.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module FruitModuleRangeConstraint.

-ifndef(_FRUITMODULERANGECONSTRAINT_HRL_).
-define(_FRUITMODULERANGECONSTRAINT_HRL_, true).

-record('FruitSalad', {
  fruits,
  servingSize
}).

-endif. %% _FRUITMODULERANGECONSTRAINT_HRL_
