/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FruitModule"
 * 	found in "FruitModule.v2.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -pdu=all`
 */

#ifndef	_Fruits_H_
#define	_Fruits_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Fruits {
	Fruits_apple	= 0,
	Fruits_orange	= 1,
	Fruits_grape	= 2,
	Fruits_banana	= 3,
	Fruits_kiwifruit	= 4
} e_Fruits;

/* Fruits */
typedef BIT_STRING_t	 Fruits_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Fruits_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Fruits;
asn_struct_free_f Fruits_free;
asn_struct_print_f Fruits_print;
asn_constr_check_f Fruits_constraint;
ber_type_decoder_f Fruits_decode_ber;
der_type_encoder_f Fruits_encode_der;
xer_type_decoder_f Fruits_decode_xer;
xer_type_encoder_f Fruits_encode_xer;
jer_type_encoder_f Fruits_encode_jer;
oer_type_decoder_f Fruits_decode_oer;
oer_type_encoder_f Fruits_encode_oer;
per_type_decoder_f Fruits_decode_uper;
per_type_encoder_f Fruits_encode_uper;
per_type_decoder_f Fruits_decode_aper;
per_type_encoder_f Fruits_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Fruits_H_ */
#include "asn_internal.h"
